// Applications/React/reactapp/src/App.js
import React from 'react';
import logo from './assets/icons/react-icon.png';
import './App.scss';

function App() {
  return (
    <div class="container">
    <div class="row">
        <div class="col-md-2"><img style={{ width:"100px",marginTop:"30px",marginLeft:"20px"}} alt="React logo" src={logo} /></div>
        <div class="col-md-10">
            <div class="header">
                <h1>Universal Style Guide</h1>
                <p>Created by Logicals.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-expand-sm sg-primary p-0">

                <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link active" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Product</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>





    <div class="row m-0">
        <div class="side">
            <h2>Branding</h2>
            <h5>Primary</h5>
            <div>
                <div class="background-demo sg-primary text-center">Background</div>
                <p class="sg-primary-text">Primary colored text</p>
                <span>Primary Icon : </span> <i class="sg-primary-text fa fa-paint-brush" aria-hidden="true"></i>

            </div>
            <h5 class="mt-3">Secondary</h5>
            <div>
                <div class="background-demo sg-secondary text-center">Background</div>
                <p class="sg-secondary-text">Secondary colored text</p>
                <span>Primary Icon : </span> <i class="sg-secondary-text fa fa-paint-brush" aria-hidden="true"></i>

            </div>
            <h5 class="mt-3">Tertiary</h5>
            <div>
                <div class="background-demo sg-tertiary text-center">Background</div>
                <p class="sg-tertiary-text">Tertiary colored text</p>
                <span>Primary Icon : </span> <i class="sg-tertiary-text fa fa-paint-brush" aria-hidden="true"></i>

            </div>
        </div>
        <div class="main">
            <p class="text-xlarge">Page Header</p>
            <p class="text-large">Section Header</p>
            <p class="text-medium">Sub Header</p>
            <p class="text-small">Label and Paragraph</p>



        </div>
    </div>

    <div class="footer">
        <p class="m-0">&copy; Techtonic Hackathon 2019</p>
    </div>
</div>
  );
}

export default App;

// Applications/Angular/AngularStyle/src/app/app.component.ts
import { Component } from '@angular/core';

import * as variables from "src/assets/_variables.js";
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'AngularStyle';

  ColorBasePrimary = variables.ColorBasePrimary;
  ColorBaseSecondary = variables.ColorBaseSecondary;
  ColorBaseTertiary = variables.ColorBaseTertiary;
  ColorBaseSuccess = variables.ColorBaseSuccess;
  ColorBaseWarning = variables.ColorBaseWarning;
  ColorBaseInfo = variables.ColorBaseInfo;
  ColorBaseDanger = variables.ColorBaseDanger;
  ColorBaseGrayLight = variables.ColorBaseGrayLight;
  ColorBaseGrayMedium = variables.ColorBaseGrayMedium;
  ColorBaseGrayDark = variables.ColorBaseGrayDark;
  ColorBaseRed = variables.ColorBaseRed;
  ColorBaseGreen = variables.ColorBaseGreen;
  ColorBaseWhite = variables.ColorBaseWhite;
  ColorFontPrimary = variables.ColorFontPrimary;
  ColorFontSecondary = variables.ColorFontSecondary;
  ColorFontTertiary = variables.ColorFontTertiary;
  SizeFontSmall = variables.SizeFontSmall;
  SizeFontMedium = variables.SizeFontMedium;
  SizeFontLarge = variables.SizeFontLarge;
  SizeFontXlarge = variables.SizeFontXlarge;
  SizeFontBase = variables.SizeFontBase;
}

<!--The content below is only a placeholder and can be replaced.-->
<!--<div style="text-align:center">
  <h1 class="hello">
    Welcome to {{ title }}!
  </h1>-->
  <!--<img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
-->

    <div class="container">
      
            <div class="col-md-12">
                <div class="header">
                    <h1>Universal Style Guide</h1>
                     <h2>Angular App</h2>
                    <p>Created by Logicals.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-sm sg-primary p-0">

                    <!-- Links -->
                    <ul class="navbar-nav">
                        <li class="nav-item ">
                            <a class="nav-link active" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Product</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>





        <div class="row m-0">
            <div class="side">
                <h2>Branding</h2>
                <h5>Primary</h5>
                <div>
                    <div class="background-demo text-center" [style.background-color]="ColorBasePrimary">Background</div>
                    <p [style.color]="ColorBasePrimary">Primary colored text</p>
                    <span>Primary Icon : </span> <i class="sg-primary-text fa fa-paint-brush" aria-hidden="true"></i>

                </div>
                <h5 class="mt-3">Secondary</h5>
                <div>
                    <div class="background-demo text-center" [style.background-color]="ColorBaseSecondary">Background</div>
                    <p [style.color]="ColorBaseSecondary">Secondary colored text</p>
                    <span>Primary Icon : </span> <i class="sg-secondary-text fa fa-paint-brush" aria-hidden="true"></i>

                </div>
                <h5 class="mt-3">Tertiary</h5>
                <div>
                    <div class="background-demo text-center" [style.background-color]="ColorBaseTertiary">Background</div>
                    <p [style.color]="ColorBaseTertiary">Tertiary colored text</p>
                    <span>Primary Icon : </span> <i class="sg-tertiary-text fa fa-paint-brush" aria-hidden="true"></i>

                </div>
            </div>
            <div class="main">
                <p [style.font-size]="SizeFontXlarge">Page Header</p>
                <p [style.font-size]="SizeFontLarge">Section Header</p>
                <p [style.font-size]="SizeFontMedium">Sub Header</p>
                <p [style.font-size]="SizeFontSmall">Label and Paragraph</p>



            </div>
        </div>

        <div class="footer">
            <p class="m-0">&copy; Techtonic Hackathon 2019</p>
        </div>
    


<router-outlet></router-outlet>
